CREATE TABLE IF NOT EXISTS organizations (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
      name VARCHAR(500) NOT NULL,
      type VARCHAR(100),  
      address TEXT,
      city VARCHAR(200),
      state VARCHAR(100),
      postcode VARCHAR(50),
      country_code VARCHAR(2),  -- ISO 3166-1 alpha-2
      contact_email VARCHAR(255),
      contact_phone VARCHAR(50),
      active BOOLEAN DEFAULT true,

      -- Timestamps (matching your existing pattern)
      cid BIGINT NOT NULL,
      ctime TIMESTAMP WITH TIME ZONE NOT NULL,
      mid BIGINT NOT NULL,
      mtime TIMESTAMP WITH TIME ZONE NOT NULL
  );

  -- ============================================================================
  -- 2. Users (E2B Version with Roles)
  -- ============================================================================
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) UNIQUE,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,

    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(128) UNIQUE NOT NULL,

    -- Auth (reuse your existing pattern)
    pwd VARCHAR(256),
    pwd_salt UUID NOT NULL DEFAULT gen_random_uuid(),
    token_salt UUID NOT NULL DEFAULT gen_random_uuid(),

    role VARCHAR(50) NOT NULL DEFAULT 'user',
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    active BOOLEAN DEFAULT true,
    last_login_at TIMESTAMP WITH TIME ZONE,

    -- Timestamps
    cid BIGINT NOT NULL,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT email_format CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    CONSTRAINT user_role_valid CHECK (role IN ('admin', 'manager', 'user', 'viewer'))
);

  CREATE INDEX idx_users_organization ON users(organization_id);
  CREATE INDEX idx_users_email ON users(email);

    -- ============================================================================
    -- 3. Safety Cases
    -- ============================================================================
CREATE TABLE if NOT EXISTS cases (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,

    -- Case identification
    safety_report_id VARCHAR(100) NOT NULL,  -- C.1.1
    version INTEGER NOT NULL DEFAULT 1,      -- C.1.1.r.1
    status VARCHAR(50) NOT NULL DEFAULT 'draft',

    -- Workflow tracking
    created_by UUID NOT NULL REFERENCES users(id),
    updated_by UUID REFERENCES users(id),
    submitted_by UUID REFERENCES users(id),
    submitted_at TIMESTAMPTZ,

    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Unique constraint: one active version per safety_report_id
    CONSTRAINT unique_safety_report_version UNIQUE (safety_report_id, version),
    CONSTRAINT case_status_valid CHECK (status IN ('draft', 'validated', 'submitted', 'archived', 'nullified'))
);

CREATE INDEX idx_cases_organization ON cases(organization_id);
CREATE INDEX idx_cases_safety_report_id ON cases(safety_report_id);
CREATE INDEX idx_cases_status ON cases(status);
CREATE INDEX idx_cases_created_by ON cases(created_by);

    -- ============================================================================
    -- 4. Case Versions (for history tracking)
    -- ============================================================================
CREATE TABLE if NOT EXISTS case_versions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    version INTEGER NOT NULL,
    snapshot JSONB NOT NULL,  -- Full case data snapshot
    changed_by UUID NOT NULL REFERENCES users(id),
    change_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT unique_case_version UNIQUE (case_id, version)
);

CREATE INDEX idx_case_versions_case ON case_versions(case_id);

    -- ============================================================================
    -- 5. Audit Logs
    -- ============================================================================
CREATE TABLE if NOT EXISTS audit_logs (
    id BIGSERIAL PRIMARY KEY,
    table_name VARCHAR(100) NOT NULL,
    record_id UUID NOT NULL,
    action VARCHAR(50) NOT NULL,
    user_id UUID NOT NULL REFERENCES users(id),
    old_values JSONB,
    new_values JSONB,
    ip_address INET,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT audit_action_valid CHECK (action IN ('CREATE', 'UPDATE', 'DELETE', 'SUBMIT', 'NULLIFY'))
);

CREATE INDEX idx_audit_logs_table_record ON audit_logs(table_name, record_id);
CREATE INDEX idx_audit_logs_user ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);
